---
- name: "Test working with vault"
  hosts: all

  # Использую плагин community.hashi_vault.hashi_vault
  # https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup
  # > ansible-galaxy collection install community.hashi_vault

  tasks:

    - name: "Extracting data from vault"
      vars:
        ansible_hashi_vault_auth_method: token
        # В этом случае токен берется из переменной окружения VAULT_TOKEN, которая передается из jenkins
      ansible.builtin.debug:
        msg: '{{ item }}'
      with_community.hashi_vault.vault_read:
        - secret/data/test


