---
- name: "Test working with vault"
  hosts: all

  # Использую плагин community.hashi_vault.hashi_vault
  # https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup
  # > ansible-galaxy collection install community.hashi_vault
  #
  # Переменную 'hashipass' получаю через опцию '-e' при вызове ansible-playbook в jenkins

  tasks:

    - name: "Extracting data from vault"
      vars:
        ansible_hashi_vault_url: "http://localhost:8200"
        ansible_hashi_vault_auth_method: userpass
        ansible_hashi_vault_username: "ansible_service"
        ansible_hashi_vault_password: "{{ hashipass }}"
      ansible.builtin.debug:
        msg: '{{ item }}'
      with_community.hashi_vault.vault_read:
        - secret/data/test
