---
- name: "Test working with vault"
  hosts: all

  # Использую плагин community.hashi_vault.hashi_vault
  # https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup
  # > ansible-galaxy collection install community.hashi_vault
  #
  # Переменную 'hashipass' получаю через опцию '-e' при вызове ansible-playbook в jenkins
  # она будет иметь наивысший приоритет и перезапишет тестовые УД, указанные в плейбуке

  vars:
    hashiuser: "hashiuser"
    hashipass: "wrong_password"

  tasks:

    - name: "Extracting data from vault"
      vars:
        ansible_hashi_vault_auth_method: userpass
        ansible_hashi_vault_username: '{{ hashiuser }}'
        ansible_hashi_vault_password: '{{ hashipass }}'
      ansible.builtin.debug:
        msg: '{{ item }}'
      with_community.hashi_vault.vault_read:
        - secret/data/test


